//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JualIn.App.Mobile.Presentation.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JualIn.App.Mobile.Presentation.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string CheckoutPage_Btn_Pay {
            get {
                return ResourceManager.GetString("CheckoutPage_Btn_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string CheckoutPage_Btn_Payment {
            get {
                return ResourceManager.GetString("CheckoutPage_Btn_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Order.
        /// </summary>
        internal static string CheckoutPage_Lbl_CurrentOrder {
            get {
                return ResourceManager.GetString("CheckoutPage_Lbl_CurrentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string CheckoutPage_Lbl_Discount {
            get {
                return ResourceManager.GetString("CheckoutPage_Lbl_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string CheckoutPage_Lbl_PageTitle {
            get {
                return ResourceManager.GetString("CheckoutPage_Lbl_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string CheckoutPage_Lbl_Payment_Amount {
            get {
                return ResourceManager.GetString("CheckoutPage_Lbl_Payment_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string CheckoutPage_Lbl_Payment_Change {
            get {
                return ResourceManager.GetString("CheckoutPage_Lbl_Payment_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string CheckoutPage_Lbl_Payment_Paid {
            get {
                return ResourceManager.GetString("CheckoutPage_Lbl_Payment_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        internal static string CheckoutPage_Lbl_PaymentMethod {
            get {
                return ResourceManager.GetString("CheckoutPage_Lbl_PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Payment.
        /// </summary>
        internal static string CheckoutPage_Lbl_PaymentTitle_Cash {
            get {
                return ResourceManager.GetString("CheckoutPage_Lbl_PaymentTitle_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string CheckoutPage_Lbl_Subtotal {
            get {
                return ResourceManager.GetString("CheckoutPage_Lbl_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string CheckoutPage_Lbl_Tax {
            get {
                return ResourceManager.GetString("CheckoutPage_Lbl_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string CheckoutPage_Lbl_Total {
            get {
                return ResourceManager.GetString("CheckoutPage_Lbl_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove this item from the cart?.
        /// </summary>
        internal static string CheckoutPage_Msg_ItemRemoveConfirmation {
            get {
                return ResourceManager.GetString("CheckoutPage_Msg_ItemRemoveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add more item!.
        /// </summary>
        internal static string CheckoutPage_Msg_ItemStockLimit {
            get {
                return ResourceManager.GetString("CheckoutPage_Msg_ItemStockLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount you paid is not enough..
        /// </summary>
        internal static string CheckoutPage_Msg_NotEnoughPaidAmount {
            get {
                return ResourceManager.GetString("CheckoutPage_Msg_NotEnoughPaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order created, waiting for the payment!.
        /// </summary>
        internal static string CheckoutPage_Msg_OrderCreated {
            get {
                return ResourceManager.GetString("CheckoutPage_Msg_OrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment failed!.
        /// </summary>
        internal static string CheckoutPage_Msg_PaymentFailed {
            get {
                return ResourceManager.GetString("CheckoutPage_Msg_PaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment successful. A transaction has been recorded!.
        /// </summary>
        internal static string CheckoutPage_Msg_PaymentSuccess {
            get {
                return ResourceManager.GetString("CheckoutPage_Msg_PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected item(s) with 0 quantity will be skipped, proceed?.
        /// </summary>
        internal static string CheckoutPage_Msg_ZeroQuantityConfirmation {
            get {
                return ResourceManager.GetString("CheckoutPage_Msg_ZeroQuantityConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        internal static string Common_Btn_AddItem {
            get {
                return ResourceManager.GetString("Common_Btn_AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Common_Btn_Delete {
            get {
                return ResourceManager.GetString("Common_Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Common_Btn_Edit {
            get {
                return ResourceManager.GetString("Common_Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        internal static string Common_Btn_ViewAll {
            get {
                return ResourceManager.GetString("Common_Btn_ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Common_Filter_All {
            get {
                return ResourceManager.GetString("Common_Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        internal static string Common_Lbl_Items_Postfix {
            get {
                return ResourceManager.GetString("Common_Lbl_Items_Postfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description.
        /// </summary>
        internal static string Common_Lbl_NoDescription {
            get {
                return ResourceManager.GetString("Common_Lbl_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found..
        /// </summary>
        internal static string Common_Lbl_NoItems {
            get {
                return ResourceManager.GetString("Common_Lbl_NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search item.
        /// </summary>
        internal static string Common_Lbl_SearchItem {
            get {
                return ResourceManager.GetString("Common_Lbl_SearchItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong, call the dev for more support!.
        /// </summary>
        internal static string Common_Msg_CommonError {
            get {
                return ResourceManager.GetString("Common_Msg_CommonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading inventories....
        /// </summary>
        internal static string Common_Msg_LoadingInventories {
            get {
                return ResourceManager.GetString("Common_Msg_LoadingInventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string Common_Msg_NotAvailable {
            get {
                return ResourceManager.GetString("Common_Msg_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold.
        /// </summary>
        internal static string DashboardPage_BestSeller_Sold {
            get {
                return ResourceManager.GetString("DashboardPage_BestSeller_Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Seller.
        /// </summary>
        internal static string DashboardPage_BestSeller_Title {
            get {
                return ResourceManager.GetString("DashboardPage_BestSeller_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Sales.
        /// </summary>
        internal static string DashboardPage_Btn_CloseSales {
            get {
                return ResourceManager.GetString("DashboardPage_Btn_CloseSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Order.
        /// </summary>
        internal static string DashboardPage_Btn_CreateOrder {
            get {
                return ResourceManager.GetString("DashboardPage_Btn_CreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction History.
        /// </summary>
        internal static string DashboardPage_Btn_OrderHistory {
            get {
                return ResourceManager.GetString("DashboardPage_Btn_OrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string DashboardPage_Btn_Products {
            get {
                return ResourceManager.GetString("DashboardPage_Btn_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Update Stock.
        /// </summary>
        internal static string DashboardPage_Btn_QuickUpdateStock {
            get {
                return ResourceManager.GetString("DashboardPage_Btn_QuickUpdateStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best seller.
        /// </summary>
        internal static string DashboardPage_Lbl_BestSeller {
            get {
                return ResourceManager.GetString("DashboardPage_Lbl_BestSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon.
        /// </summary>
        internal static string DashboardPage_Lbl_Greeting_Afternoon {
            get {
                return ResourceManager.GetString("DashboardPage_Lbl_Greeting_Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        internal static string DashboardPage_Lbl_Greeting_Evening {
            get {
                return ResourceManager.GetString("DashboardPage_Lbl_Greeting_Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        internal static string DashboardPage_Lbl_Greeting_Morning {
            get {
                return ResourceManager.GetString("DashboardPage_Lbl_Greeting_Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string DashboardPage_Lbl_Greeting_Night {
            get {
                return ResourceManager.GetString("DashboardPage_Lbl_Greeting_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s your business overview today.
        /// </summary>
        internal static string DashboardPage_Lbl_Greeting_Postfix {
            get {
                return ResourceManager.GetString("DashboardPage_Lbl_Greeting_Postfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string DashboardPage_Lbl_Greeting_Prefix {
            get {
                return ResourceManager.GetString("DashboardPage_Lbl_Greeting_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        internal static string DashboardPage_RevenuePreview_Filter_Profit {
            get {
                return ResourceManager.GetString("DashboardPage_RevenuePreview_Filter_Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        internal static string DashboardPage_RevenuePreview_Filter_Revenue {
            get {
                return ResourceManager.GetString("DashboardPage_RevenuePreview_Filter_Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated at.
        /// </summary>
        internal static string DashboardPage_RevenuePreview_LastUpdated {
            get {
                return ResourceManager.GetString("DashboardPage_RevenuePreview_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Chart.
        /// </summary>
        internal static string DashboardPage_TransactionChart_Title {
            get {
                return ResourceManager.GetString("DashboardPage_TransactionChart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string HomeTab_Dashboard {
            get {
                return ResourceManager.GetString("HomeTab_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string HomeTab_InventoryMangement {
            get {
                return ResourceManager.GetString("HomeTab_InventoryMangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp.
        /// </summary>
        internal static string Inventory_Lbl_Expire {
            get {
                return ResourceManager.GetString("Inventory_Lbl_Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        internal static string Inventory_Lbl_Sku {
            get {
                return ResourceManager.GetString("Inventory_Lbl_Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string Inventory_Lbl_Stock {
            get {
                return ResourceManager.GetString("Inventory_Lbl_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string Inventory_Lbl_StockState_Expired {
            get {
                return ResourceManager.GetString("Inventory_Lbl_StockState_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In stock.
        /// </summary>
        internal static string Inventory_Lbl_StockState_InStock {
            get {
                return ResourceManager.GetString("Inventory_Lbl_StockState_InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low stock.
        /// </summary>
        internal static string Inventory_Lbl_StockState_LowStock {
            get {
                return ResourceManager.GetString("Inventory_Lbl_StockState_LowStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items.
        /// </summary>
        internal static string InventoryDetail_Filter_AllItems {
            get {
                return ResourceManager.GetString("InventoryDetail_Filter_AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string InventoryDetail_Filter_Expired {
            get {
                return ResourceManager.GetString("InventoryDetail_Filter_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low stock.
        /// </summary>
        internal static string InventoryDetail_Filter_LowStock {
            get {
                return ResourceManager.GetString("InventoryDetail_Filter_LowStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch #.
        /// </summary>
        internal static string InventoryDetail_Lbl_BatchNumber {
            get {
                return ResourceManager.GetString("InventoryDetail_Lbl_BatchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Inventory.
        /// </summary>
        internal static string InventoryDetail_Lbl_DeleteInventoryDialogTitle {
            get {
                return ResourceManager.GetString("InventoryDetail_Lbl_DeleteInventoryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Date.
        /// </summary>
        internal static string InventoryDetail_Lbl_ExpiredDate {
            get {
                return ResourceManager.GetString("InventoryDetail_Lbl_ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire.
        /// </summary>
        internal static string InventoryDetail_Lbl_ExpiredDate_Short {
            get {
                return ResourceManager.GetString("InventoryDetail_Lbl_ExpiredDate_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Stock Update.
        /// </summary>
        internal static string InventoryDetail_Lbl_LastStockUpdate {
            get {
                return ResourceManager.GetString("InventoryDetail_Lbl_LastStockUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Detail.
        /// </summary>
        internal static string InventoryDetail_Lbl_PageTitle {
            get {
                return ResourceManager.GetString("InventoryDetail_Lbl_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string InventoryDetail_Lbl_Price {
            get {
                return ResourceManager.GetString("InventoryDetail_Lbl_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date.
        /// </summary>
        internal static string InventoryDetail_Lbl_PurchaseDate {
            get {
                return ResourceManager.GetString("InventoryDetail_Lbl_PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        internal static string InventoryDetail_Lbl_Sku {
            get {
                return ResourceManager.GetString("InventoryDetail_Lbl_Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string InventoryDetail_Lbl_Stock {
            get {
                return ResourceManager.GetString("InventoryDetail_Lbl_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Threshold.
        /// </summary>
        internal static string InventoryDetail_Lbl_StockThreshold {
            get {
                return ResourceManager.GetString("InventoryDetail_Lbl_StockThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        internal static string InventoryDetail_Lbl_StockThreshold_Short {
            get {
                return ResourceManager.GetString("InventoryDetail_Lbl_StockThreshold_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string InventoryDetail_Lbl_Supplier {
            get {
                return ResourceManager.GetString("InventoryDetail_Lbl_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC.
        /// </summary>
        internal static string InventoryDetail_Lbl_Upc {
            get {
                return ResourceManager.GetString("InventoryDetail_Lbl_Upc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory will be deleted and can&apos;t be undone. Are you sure?.
        /// </summary>
        internal static string InventoryDetail_Msg_ConfirmDeleteInventory {
            get {
                return ResourceManager.GetString("InventoryDetail_Msg_ConfirmDeleteInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory has been deleted successfully.
        /// </summary>
        internal static string InventoryDetail_Msg_InventoryDeleted {
            get {
                return ResourceManager.GetString("InventoryDetail_Msg_InventoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item will not available soon!.
        /// </summary>
        internal static string InventoryDetail_Msg_StockThresholdExceed {
            get {
                return ResourceManager.GetString("InventoryDetail_Msg_StockThresholdExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string InventoryForm_Btn_AddCategory {
            get {
                return ResourceManager.GetString("InventoryForm_Btn_AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string InventoryForm_Btn_Save {
            get {
                return ResourceManager.GetString("InventoryForm_Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new category.
        /// </summary>
        internal static string InventoryForm_Lbl_AddCategory_Body {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_AddCategory_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Number.
        /// </summary>
        internal static string InventoryForm_Lbl_BatchNumber {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_BatchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string InventoryForm_Lbl_Category {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (optional).
        /// </summary>
        internal static string InventoryForm_Lbl_Description {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Date.
        /// </summary>
        internal static string InventoryForm_Lbl_ExpiredDate {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string InventoryForm_Lbl_ItemName {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Stock Update.
        /// </summary>
        internal static string InventoryForm_Lbl_LastStockUpdate {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_LastStockUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Form.
        /// </summary>
        internal static string InventoryForm_Lbl_PageTitle {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string InventoryForm_Lbl_Price {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date.
        /// </summary>
        internal static string InventoryForm_Lbl_PurchaseDate {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU (optional).
        /// </summary>
        internal static string InventoryForm_Lbl_Sku {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string InventoryForm_Lbl_Stock {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Threshold.
        /// </summary>
        internal static string InventoryForm_Lbl_StockThreshold {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_StockThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string InventoryForm_Lbl_StockUnit {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_StockUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string InventoryForm_Lbl_Supplier {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC (optional).
        /// </summary>
        internal static string InventoryForm_Lbl_Upc {
            get {
                return ResourceManager.GetString("InventoryForm_Lbl_Upc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category has been added!.
        /// </summary>
        internal static string InventoryForm_Msg_AddedNewCategory {
            get {
                return ResourceManager.GetString("InventoryForm_Msg_AddedNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string InventoryManagementPage_Btn_Import {
            get {
                return ResourceManager.GetString("InventoryManagementPage_Btn_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string InventoryManagementPage_Btn_Scan {
            get {
                return ResourceManager.GetString("InventoryManagementPage_Btn_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Management.
        /// </summary>
        internal static string InventoryManagementPage_Lbl_PageTitle {
            get {
                return ResourceManager.GetString("InventoryManagementPage_Lbl_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string OrderHistoryPage_Btn_Confirm {
            get {
                return ResourceManager.GetString("OrderHistoryPage_Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string OrderHistoryPage_Lbl_Confirmed {
            get {
                return ResourceManager.GetString("OrderHistoryPage_Lbl_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        internal static string OrderHistoryPage_Lbl_OrderId {
            get {
                return ResourceManager.GetString("OrderHistoryPage_Lbl_OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order History.
        /// </summary>
        internal static string OrderHistoryPage_Lbl_PageTitle {
            get {
                return ResourceManager.GetString("OrderHistoryPage_Lbl_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        internal static string OrderHistoryPage_Menu_Refund {
            get {
                return ResourceManager.GetString("OrderHistoryPage_Menu_Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string PaymentMethod_Lbl_BankTransfer {
            get {
                return ResourceManager.GetString("PaymentMethod_Lbl_BankTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string PaymentMethod_Lbl_Cash {
            get {
                return ResourceManager.GetString("PaymentMethod_Lbl_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string PaymentMethod_Lbl_CreditCard {
            get {
                return ResourceManager.GetString("PaymentMethod_Lbl_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Card.
        /// </summary>
        internal static string PaymentMethod_Lbl_DebitCard {
            get {
                return ResourceManager.GetString("PaymentMethod_Lbl_DebitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string PointOfSalePage_Btn_Checkout {
            get {
                return ResourceManager.GetString("PointOfSalePage_Btn_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Management.
        /// </summary>
        internal static string PointOfSalePage_Lbl_PageTitle {
            get {
                return ResourceManager.GetString("PointOfSalePage_Lbl_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add more item!.
        /// </summary>
        internal static string PointOfSalePage_Msg_ItemStockLimit {
            get {
                return ResourceManager.GetString("PointOfSalePage_Msg_ItemStockLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string Product_Lbl_Stock {
            get {
                return ResourceManager.GetString("Product_Lbl_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Stock Output.
        /// </summary>
        internal static string ProductComponent_Lbl_ProductStockOutput {
            get {
                return ResourceManager.GetString("ProductComponent_Lbl_ProductStockOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Stock Used.
        /// </summary>
        internal static string ProductComponent_Lbl_QuantityPerUnit {
            get {
                return ResourceManager.GetString("ProductComponent_Lbl_QuantityPerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Price.
        /// </summary>
        internal static string ProductDetail_Lbl_CapitalPrice {
            get {
                return ResourceManager.GetString("ProductDetail_Lbl_CapitalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string ProductDetail_Lbl_Category {
            get {
                return ResourceManager.GetString("ProductDetail_Lbl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product.
        /// </summary>
        internal static string ProductDetail_Lbl_DeleteProductDialogTitle {
            get {
                return ResourceManager.GetString("ProductDetail_Lbl_DeleteProductDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string ProductDetail_Lbl_Discount {
            get {
                return ResourceManager.GetString("ProductDetail_Lbl_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string ProductDetail_Lbl_Margin {
            get {
                return ResourceManager.GetString("ProductDetail_Lbl_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string ProductDetail_Lbl_Stock {
            get {
                return ResourceManager.GetString("ProductDetail_Lbl_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product will be deleted and can&apos;t be undone. Are you sure?.
        /// </summary>
        internal static string ProductDetail_Msg_ConfirmDeleteProduct {
            get {
                return ResourceManager.GetString("ProductDetail_Msg_ConfirmDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has been deleted successfully.
        /// </summary>
        internal static string ProductDetail_Msg_ProductDeleted {
            get {
                return ResourceManager.GetString("ProductDetail_Msg_ProductDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ProductForm_Btn_AddCategory {
            get {
                return ResourceManager.GetString("ProductForm_Btn_AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ProductForm_Btn_AddComponent {
            get {
                return ResourceManager.GetString("ProductForm_Btn_AddComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ProductForm_Btn_Save {
            get {
                return ResourceManager.GetString("ProductForm_Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new category.
        /// </summary>
        internal static string ProductForm_Lbl_AddCategory_Body {
            get {
                return ResourceManager.GetString("ProductForm_Lbl_AddCategory_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Price.
        /// </summary>
        internal static string ProductForm_Lbl_CapitalPrice {
            get {
                return ResourceManager.GetString("ProductForm_Lbl_CapitalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string ProductForm_Lbl_Category {
            get {
                return ResourceManager.GetString("ProductForm_Lbl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        internal static string ProductForm_Lbl_Components {
            get {
                return ResourceManager.GetString("ProductForm_Lbl_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string ProductForm_Lbl_Discount {
            get {
                return ResourceManager.GetString("ProductForm_Lbl_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string ProductForm_Lbl_Margin {
            get {
                return ResourceManager.GetString("ProductForm_Lbl_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string ProductForm_Lbl_PageTitle {
            get {
                return ResourceManager.GetString("ProductForm_Lbl_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Price.
        /// </summary>
        internal static string ProductForm_Lbl_Price {
            get {
                return ResourceManager.GetString("ProductForm_Lbl_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description (optional).
        /// </summary>
        internal static string ProductForm_Lbl_ProductDescription {
            get {
                return ResourceManager.GetString("ProductForm_Lbl_ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string ProductForm_Lbl_ProductName {
            get {
                return ResourceManager.GetString("ProductForm_Lbl_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string ProductForm_Lbl_Stock {
            get {
                return ResourceManager.GetString("ProductForm_Lbl_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category has been added!.
        /// </summary>
        internal static string ProductForm_Msg_AddedNewCategory {
            get {
                return ResourceManager.GetString("ProductForm_Msg_AddedNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Management.
        /// </summary>
        internal static string ProductManagementPage_Lbl_PageTitle {
            get {
                return ResourceManager.GetString("ProductManagementPage_Lbl_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string ProductSummary_Lbl_Category {
            get {
                return ResourceManager.GetString("ProductSummary_Lbl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string ProductSummary_Lbl_Margin {
            get {
                return ResourceManager.GetString("ProductSummary_Lbl_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string ProductSummary_Lbl_Price {
            get {
                return ResourceManager.GetString("ProductSummary_Lbl_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string ProductSummary_Lbl_Stock {
            get {
                return ResourceManager.GetString("ProductSummary_Lbl_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string SignInPage_Btn_ForgotPassword {
            get {
                return ResourceManager.GetString("SignInPage_Btn_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInPage_Btn_SignIn {
            get {
                return ResourceManager.GetString("SignInPage_Btn_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In with Facebook.
        /// </summary>
        internal static string SignInPage_Btn_SignInWithFacebook {
            get {
                return ResourceManager.GetString("SignInPage_Btn_SignInWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In with Google.
        /// </summary>
        internal static string SignInPage_Btn_SignInWithGoogle {
            get {
                return ResourceManager.GetString("SignInPage_Btn_SignInWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignInPage_Btn_SignUp {
            get {
                return ResourceManager.GetString("SignInPage_Btn_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string SignInPage_Lbl_DontHaveAccount {
            get {
                return ResourceManager.GetString("SignInPage_Lbl_DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string SignInPage_Lbl_FormTitle_Email {
            get {
                return ResourceManager.GetString("SignInPage_Lbl_FormTitle_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignInPage_Lbl_FormTitle_Password {
            get {
                return ResourceManager.GetString("SignInPage_Lbl_FormTitle_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or continue with.
        /// </summary>
        internal static string SignInPage_Lbl_SocialSignInDivider {
            get {
                return ResourceManager.GetString("SignInPage_Lbl_SocialSignInDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with your email or social account.
        /// </summary>
        internal static string SignInPage_Lbl_SubTitle {
            get {
                return ResourceManager.GetString("SignInPage_Lbl_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back.
        /// </summary>
        internal static string SignInPage_Lbl_Title {
            get {
                return ResourceManager.GetString("SignInPage_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need you to confirm your email address before you can sign in. Please check your inbox for our verification email..
        /// </summary>
        internal static string SignInPage_Msg_EmailNotConfirmed {
            get {
                return ResourceManager.GetString("SignInPage_Msg_EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string SignUpPage_Btn_Next {
            get {
                return ResourceManager.GetString("SignUpPage_Btn_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string SignUpPage_Btn_Register {
            get {
                return ResourceManager.GetString("SignUpPage_Btn_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignUpPage_Btn_SignIn {
            get {
                return ResourceManager.GetString("SignUpPage_Btn_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up with Facebook.
        /// </summary>
        internal static string SignUpPage_Btn_SignUpWithFacebook {
            get {
                return ResourceManager.GetString("SignUpPage_Btn_SignUpWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up with Google.
        /// </summary>
        internal static string SignUpPage_Btn_SignUpWithGoogle {
            get {
                return ResourceManager.GetString("SignUpPage_Btn_SignUpWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string SignUpPage_Lbl_AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("SignUpPage_Lbl_AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category.
        /// </summary>
        internal static string SignUpPage_Lbl_FormTitle_BusinessCategory {
            get {
                return ResourceManager.GetString("SignUpPage_Lbl_FormTitle_BusinessCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        internal static string SignUpPage_Lbl_FormTitle_BusinessName {
            get {
                return ResourceManager.GetString("SignUpPage_Lbl_FormTitle_BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string SignUpPage_Lbl_FormTitle_ConfirmPassword {
            get {
                return ResourceManager.GetString("SignUpPage_Lbl_FormTitle_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string SignUpPage_Lbl_FormTitle_Email {
            get {
                return ResourceManager.GetString("SignUpPage_Lbl_FormTitle_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string SignUpPage_Lbl_FormTitle_FirstName {
            get {
                return ResourceManager.GetString("SignUpPage_Lbl_FormTitle_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string SignUpPage_Lbl_FormTitle_LastName {
            get {
                return ResourceManager.GetString("SignUpPage_Lbl_FormTitle_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignUpPage_Lbl_FormTitle_Password {
            get {
                return ResourceManager.GetString("SignUpPage_Lbl_FormTitle_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        internal static string SignUpPage_Lbl_InvalidEmail {
            get {
                return ResourceManager.GetString("SignUpPage_Lbl_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not match.
        /// </summary>
        internal static string SignUpPage_Lbl_PasswordNotMatch {
            get {
                return ResourceManager.GetString("SignUpPage_Lbl_PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or sign up with.
        /// </summary>
        internal static string SignUpPage_Lbl_SocialSignUpDivider {
            get {
                return ResourceManager.GetString("SignUpPage_Lbl_SocialSignUpDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up now and boost your business efficiency!.
        /// </summary>
        internal static string SignUpPage_Lbl_SubTitle {
            get {
                return ResourceManager.GetString("SignUpPage_Lbl_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Registration.
        /// </summary>
        internal static string SignUpPage_Lbl_Title {
            get {
                return ResourceManager.GetString("SignUpPage_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account registration successful.
        /// </summary>
        internal static string SignUpPage_Msg_AccountRegistered {
            get {
                return ResourceManager.GetString("SignUpPage_Msg_AccountRegistered", resourceCulture);
            }
        }
    }
}
